# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
email: unbox-contact@posteo.de
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: ma__vo
permalink: /blog/:title
url: "www.unbox-blackbox.org"

# Build settings
highlighter: rouge
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-bootstrap-sass
  - jekyll-lunr-js-search
  - jekyll-email-protect
  - jekyll-sitemap
  - jekyll-seo-tag
  #- jekyll-autoprefixer
exclude:
  - Gemfile
  - Gemfile.lock
  - commands.txt
  - start_serve.bat
  - start_watch.bat

plugins:
  - jekyll-seo-tag

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          assets/_scss
  #style:            :compressed

repository: 'unbox-blackbox'

title: "Unbox Blackbox"
description: "Texte & Talks zur Aneignung von Technik durch die Zivilgesellschaft - by Maximilian Voigt"
logo: "/assets/img/static/mavo.jpg"
twitter:
  username: ma__vo
  card: summary_large_image
lang: "de_DE"
